#!/bin/bash

_F=$(mktemp)

function show() {
 if [ "${pretty}" ]; then
  cat ${_F}|json_PP
 else
  cat ${_F}
  printf "\n"
 fi
}

function usage() {
   printf "Usage: checkSAS [-v][-p][-m <timeout>]\n"
   printf "\t-v : verbose information\n"
   printf "\t-p : pretty print JSON\n"
   printf "\t-m : set max connection time (timeout after m sec)\n"
}

max=10
while [ "$#" -gt 0 ]; do
  case "$1" in
    -v) verbose=1; shift 1;;
    -p) pretty=1; shift 1;;
    -m) max=$2; shift 2;;
    *) echo "unknown option: $1" >&2; usage; exit 1;;
  esac
done

printf "=== Staging/.126 ===\n"
curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: 54c968db-c602-4cf0-a51e-9d957c8c7886' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://192.168.100.126:8080/sasmd/manager/info' -o ${_F} && show $?
if [ "${verbose}" ]; then
 curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: 54c968db-c602-4cf0-a51e-9d957c8c7886' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://192.168.100.126:8080/sasmd/manager/health' -o ${_F} && show $?
fi
printf "\n=== Demo/.74===\n"
curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: 54c968db-c602-4cf0-a51e-9d957c8c7886' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://192.168.100.74:8080/sasmd/manager/info' -o ${_F} && show $?
if [ "${verbose}" ]; then
 curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: 54c968db-c602-4cf0-a51e-9d957c8c7886' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://192.168.100.74:8080/sasmd/manager/health' -o ${_F} && show $?
fi

printf "\n=== Dev/.91 ===\n"
curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: 54c968db-c602-4cf0-a51e-9d957c8c7886' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://192.168.100.91:8080/sasmd/manager/info' -o ${_F} && show $?
if [ "${verbose}" ]; then
 curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: 54c968db-c602-4cf0-a51e-9d957c8c7886' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://192.168.100.91:8080/sasmd/manager/health' -o ${_F} && show $?
fi

printf "\n=== localhost/.9999===\n"
curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: defaultKey' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://localhost:9999/sasmd/manager/info' -o ${_F} && show $?
if [ "${verbose}" ]; then
 curl -m ${max} -f -s -S -X GET --header 'Accept: application/vnd.spring-boot.actuator.v1+json' --header 'api-key: defaultKey' --header 'Authorization: Basic YWRtaW5Ac3lzdGVtOmFkbWlu' 'http://localhost:9999/sasmd/manager/health' -o ${_F} && show $?
fi

rm -f ${_F}
#
##
