#!/bin/bash

#
# changes:
# - modify for use with WD myBook device
# - using rsync to sync local storage with WD 'mybooklive'
# - use-case only to store/backup media files (music,pictures,movies)
#

# bash debugging:
#set -v

SELF=`basename $0` 

function error() {
	echo ${SELF} " - [ERROR]: " $* 
	echo ${SELF} " - exiting."
	exit 1
}

if [ ! -e .sync ]; then
	error "No '.sync' file found."
fi
SYNC_DIR=$(cat .sync|grep -v -e '^#')
HOST=${SYNC_DIR%:*}
DIR=${SYNC_DIR#*:}

if [ "push" = ${SELF} ]; then
	SRC=`pwd`/
	DST="${SYNC_DIR}"
fi
if [ "pull" = ${SELF} ]; then
	SRC="${SYNC_DIR}"
	DST=`pwd`/
fi

printf "INFO: use '-n' for 'dry-run'\n"
printf "INFO: use '--del' to delete extranous files from dest dirs\n\n"
printf "INFO: about to ${SELF}\n\t from ${SRC}\n\t to ${DST}\n\n"
echo -n "Do you want to (C)ontinue or (A)bort? "
read -e -n 1 IN
printf "\n"
if [ "C" != "${IN}" ]; then
	echo "aborting ..."
	exit 1
fi

# build ignore list
TMPFILE=`mktemp /tmp/${SELF}.XXXXXX` || exit 1

if [ -e ${HOME}/.mysyncignore ]; then
	cat ${HOME}/.mysyncignore >> ${TMPFILE}
fi
if [ -e ./.mysyncignore ]; then
	cat ./.mysyncignore >> ${TMPFILE}
fi

# exec cmd: IMPORTANT -- keep echo and cmd in sync ...
echo rsync $* -rplt --chmod=D777,F666 --progress -e \"ssh -l sshd\" --exclude=.mysyncignore --exclude-from=${TMPFILE} "${SRC}" "${DST}"
rsync $* -rplt --chmod=D777,F666 --progress -e "ssh -l sshd" --exclude=.mysyncignore --exclude-from=${TMPFILE} "${SRC}" "${DST}"

if [ "push" = ${SELF} ]; then
	printf "Repair group on WD Mycloud (cannot use --group):\n"
	ssh sshd@${HOST} "find ${DIR} ! -group share -exec chown :share {} \;"
fi

#cleanup
rm -f ${TMPFILE}

exit 0
#
##
