#!/bin/bash

#
# Cleanup utility after importing from NIKON D3200 SD
#

# 1. chmod 644 - remove the x bit
# 2. change ending to lower-case (JPG,MOV)->(jpg,mov)
# 3. filename: add file creation date to filename

# process JPG
for f in DSC_*.JPG; do 
	mv -n -v $f `stat -t "%F-%H.%M.%S" -f "%SB-%N" ${f}|sed 's/\.JPG/\.jpg/'`
done

# process MOV
for f in DSC_*.MOV; do 
	mv -n -v $f `stat -t "%F-%H.%M.%S" -f "%SB-%N" ${f}|sed 's/\.MOV/\.mov/'`
done
