#!/bin/bash

function usage() {
	echo "Usage:: `basename $0` <Directory> [-n] :: rsync the current directory (pwd) to Public/Shared Pictures/<Directory>"
}

if [ -z "$1" -o "$1" = "-n" ]; then
	usage;
	exit 1
fi

TMPFILE=`mktemp /tmp/SYNCBOOK.XXXXXX` || exit 1

# build ignore list
cat > ${TMPFILE}<<-XXX
	.*
	*~
	.git*
	.BACKUP
	.sync
	.DS_Store
	._*
	.Apple*
	Icon*
XXX

#printf -v SRC %q "`pwd`/"
SRC="`pwd`/"
printf -v DST %q "$1"
rsync -rltpz $2 --progress -e "ssh -l root" --exclude-from=${TMPFILE} "${SRC}" mybooklive:"/shares/Public/Shared\ Pictures/${DST}/"

rm -f ${TMPFILE}
#
##
